spring:
  profiles:
    active: dev
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: dev
  zipkin:
    enabled: false
application:
  hostname: http://localhost:8090
  signing.key: microservice-kubernetes-cluster-auth
  user:
    username: user
    password: user
  admin:
    username: admin
    password: admin
  jwt:
    client:
      id: kubernetes-cluster
      secret: secret
    access.token.validity: 1200
    refresh.token.validity: 12000
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:/etc/config/application-prod.yml
