spring:
  profiles:
    active: dev
server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile: dev
jwt:
  clientId: kubernetes-cluster
  client-secret: secret
  accessTokenValiditySeconds: 1200
  refreshTokenValiditySeconds: 12000
