spring:
  profiles:
    active: dev
  application:
    name: persistence
  flyway:
    enabled: true
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:messaging
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration/h2
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/messaging
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    locations: classpath:db/migration/mariadb
server:
  servlet:
    context-path: /persistence