spring:
  profiles:
    active: dev
  application:
    name: persistence
  flyway:
    enabled: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
keycloak:
  realm: master
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
kafka:
  bootstrapAddress: localhost:9092
  groupId: persistenceApp
  topic: auditing
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:messaging
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration/h2
logging:
  level:
    root: INFO
    ch.valtech: DEBUG
keycloak:
  auth-server-url: http://localhost:8180/auth
application:
  token.url: http://localhost:8180/auth/realms/master/protocol/openid-connect/token
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:/etc/config/application-prod.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/messaging
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    locations: classpath:db/migration/mariadb
server:
  servlet:
    context-path: /persistence