spring:
  application:
    name: persistence
  datasource:
    url: jdbc:mariadb://localhost:3306/messaging
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081
