apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-config
  namespace: default
data:
  application-prod.yml: |-
    application:
      hostname: http://vtch-aks-demo.duckdns.org
      upload.path: /etc/file-storage/uploads/