apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-cloud-config
  namespace: default
data:
  application-cloud.yml: |-
    application:
      cloud:
        storage:
          account.name: vtchk8sblueprinttfst
          container.name: filestorage
          account.key: ${STORAGE_ACCOUNT_KEY}
          connection: ${STORAGE_CONNECTION}