apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-cloud-config
  namespace: default
data:
  application-cloud.yml: |-
    server:
      servlet:
        context-path: /filestorage
    spring:
      zipkin:
        baseUrl: http://zipkin.istio-system.svc.cluster.local:9411/
    keycloak:
      auth-server-url: https://vtch-aks-demo.duckdns.org/auth
    application:
      persistence.url: http://persistence-service.default.svc.cluster.local:8081/persistence/api/v1/messages
      token.url: https://vtch-aks-demo.duckdns.org/auth/realms/master/protocol/openid-connect/token
      cloud:
        storage:
          account.name: vtchk8sblueprinttfst
          container.name: filestorage
          account.key: ${STORAGE_ACCOUNT_KEY}
          connection: ${STORAGE_CONNECTION}