apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage
  namespace: default
  labels:
    app: file-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-storage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: file-storage
    spec:
      containers:
        - name: file-storage
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
            - name: STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  key: STORAGE_ACCOUNT_KEY
                  name: file-storage-cloud-secret
            - name: STORAGE_CONNECTION
              valueFrom:
                secretKeyRef:
                  key: STORAGE_CONNECTION
                  name: file-storage-cloud-secret
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 2
          volumeMounts:
#            - name: application-config
#              mountPath: "/etc/config/"
            - name: application-cloud-config
              mountPath: "/etc/config/cloud/"
#            - name: file-storage-pv
#              mountPath: "/etc/file-storage/uploads"
      volumes:
#        - name: file-storage-pv
#          persistentVolumeClaim:
#            claimName: file-storage-pvc
#        - name: application-config
#          configMap:
#            name: file-storage-config
#            items:
#              - key: application-prod.yml
#                path: application-prod.yml
        - name: application-cloud-config
          configMap:
            name: file-storage-cloud-config
            items:
              - key: application-cloud.yml
                path: application-cloud.yml
