apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-cloud-config
  namespace: default
data:
  application-cloud.yml: |-
    server:
      servlet:
        context-path: /filestorage
    grpc:
      client:
        persistence:
          address: dns:///persistence-service.default.svc.cluster.local:9090
    application:
      persistence.url: http://persistence-service.default.svc.cluster.local:8081/persistence/api/v1/messages
      token.url: https://vtch-aks-demo.duckdns.org/auth/realms/cluster/protocol/openid-connect/token
      functions.key: ${FUNCTIONS_KEY}
      cloud:
        storage:
          account.name: vtchk8sblueprinttfst
          container.name: filestorage
          account.key: ${STORAGE_ACCOUNT_KEY}
          connection: ${STORAGE_CONNECTION}
      kafka:
        bootstrapAddress: kafka-cluster-kafka-brokers.default.svc.cluster.local:9092
        topic: auditing
        stream:
          topic: reverse-auditing