apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage
  namespace: default
  labels:
    app: file-storage
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: file-storage
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: file-storage
    spec:
      containers:
        - name: file-storage
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud"
            - name: STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  key: STORAGE_ACCOUNT_KEY
                  name: file-storage-cloud-secret
            - name: STORAGE_CONNECTION
              valueFrom:
                secretKeyRef:
                  key: STORAGE_CONNECTION
                  name: file-storage-cloud-secret
          livenessProbe:
            httpGet:
              path: /filestorage/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /filestorage/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
#            - name: application-config
#              mountPath: "/etc/config/"
            - name: application-cloud-config
              mountPath: "/etc/config/cloud/"
#            - name: file-storage-pv
#              mountPath: "/etc/file-storage/uploads"
      volumes:
#        - name: file-storage-pv
#          persistentVolumeClaim:
#            claimName: file-storage-pvc
#        - name: application-config
#          configMap:
#            name: file-storage-config
#            items:
#              - key: application-prod.yml
#                path: application-prod.yml
        - name: application-cloud-config
          configMap:
            name: file-storage-cloud-config
            items:
              - key: application-cloud.yml
                path: application-cloud.yml
