apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage
  namespace: default
  labels:
    app: file-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-storage
  template:
    metadata:
      labels:
        app: file-storage
    spec:
      containers:
        - name: file-storage
          image: vtchk8sblueprintrg.azurecr.io/microservice-kubernetes-cluster/file-storage:latest
          imagePullPolicy: Always
          env:
            - name: UPLOAD_PATH
              value: /etc/file-storage/uploads
          ports:
            - containerPort: 80
          volumeMounts:
            - name: file-storage-pv
              mountPath: /etc/file-storage/uploads
      volumes:
        - name: file-storage-pv
          persistentVolumeClaim:
            claimName: file-storage-pvc