apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-config
  namespace: default
data:
  application-prod.yml: |-
    spring:
      zipkin:
        baseUrl: http://zipkin.istio-system.svc.cluster.local:9411/
    keycloak:
      auth-server-url: https://vtch-aks-demo.duckdns.org/auth
    application:
      hostname: http://vtch-aks-demo.duckdns.org
      upload.path: /etc/file-storage/uploads/
      persistence.url: http://persistence-service.default.svc.cluster.local:8081/persistence/api/v1/messages
      token.url: https://vtch-aks-demo.duckdns.org/auth/realms/master/protocol/openid-connect/token