apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-config
  namespace: default
data:
  hostname: http://vtch-aks-demo.duckdns.org
  uploadPath: /etc/file-storage/uploads/