apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-cloud-config
  namespace: default
data:
  application-cloud.yml: |-
    server:
      servlet:
        context-path: /filestorage
    spring:
      zipkin:
        baseUrl: http://zipkin.istio-system.svc.cluster.local:9411/
    keycloak:
      auth-server-url: https://vtch-aks-demo.duckdns.org/auth
    security:
      oauth2:
        client:
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
        resource:
          token-info-uri: http://authentication.default.svc.cluster.local:8080/auth/oauth/check_token
          preferTokenInfo: true
        basic:
          enabled: false
    application:
      persistence.url: http://persistence-service.default.svc.cluster.local:8081/persistence/api/v1/messages
      token.url: https://vtch-aks-demo.duckdns.org/auth/oauth/token
      cloud:
        storage:
          account.name: vtchk8sblueprinttfst
          container.name: filestorage
          account.key: ${STORAGE_ACCOUNT_KEY}
          connection: ${STORAGE_CONNECTION}
