apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-cloud-config
  namespace: default
data:
  application-cloud.yml: |-
    server:
      servlet:
        context-path: /filestorage
    security:
      oauth2:
        client:
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
        resource:
          token-info-uri: http://authentication.default.svc.cluster.local:8080/auth/oauth/check_token
          preferTokenInfo: true
        basic:
          enabled: false
    application:
      cloud:
        storage:
          account.name: vtchk8sblueprinttfst
          container.name: filestorage
          account.key: ${STORAGE_ACCOUNT_KEY}
          connection: ${STORAGE_CONNECTION}