apiVersion: v1
kind: Service
metadata:
  name: file-storage
  namespace: default
  labels:
    app: file-storage
    service: file-storage
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: 'filestorage/actuator/prometheus'
      prometheus.io/port: '8080'
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: file-storage