apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-cloud-config
  namespace: default
data:
  application-cloud.yml: |-
    security:
      oauth2:
        client:
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
        resource:
          token-info-uri: http://10.244.2.86:8090/auth/oauth/check_token
          preferTokenInfo: true
        basic:
          enabled: false
    application:
      swaggerApiPrefix: /filestorage/
      cloud:
        storage:
          account.name: vtchk8sblueprinttfst
          container.name: filestorage
          account.key: ${STORAGE_ACCOUNT_KEY}
          connection: ${STORAGE_CONNECTION}