spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
---
spring:
  config:
    activate:
      on-profile: dev
hostname: http://localhost:8080
uploadPath: /tmp/internal/kubernetes/uploads/
storageAccountName: vtchk8sblueprinttfst
storageContainerName: fileStorage
secret:
  storageAccountKey: secret
  storageConnection: secret
---
spring:
  config:
    activate:
      on-profile: prod
    import: configtree:/etc/config/
---
spring:
  config:
    activate:
      on-profile: cloud
    import: configtree:/etc/config/cloud/