spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
management:
  endpoints:
    web:
      exposure:
        include: "*"
keycloak:
  realm: master
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
---
spring:
  config:
    activate:
      on-profile: dev
  zipkin:
    enabled: false
logging:
  level:
    root: INFO
    ch.valtech: DEBUG
keycloak:
  auth-server-url: http://localhost:8180/auth
application:
  hostname: http://localhost:8080
  upload.path: /tmp/internal/kubernetes/uploads/
  persistence.url: http://localhost:8081/api/v1/messages
  token.url: http://localhost:8090/oauth/token
  cloud:
    storage:
      account.name: vtchk8sblueprinttfst
      container.name: filestorage
      account.key: secret
      connection: secret
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:/etc/config/application-prod.yml
---
spring:
  config:
    activate:
      on-profile: cloud
    import: file:/etc/config/cloud/application-cloud.yml
