spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
server:
  servlet:
    context-path: /lukas
---
spring:
  config:
    activate:
      on-profile: dev
security:
  oauth2:
    client:
      clientId: kubernetes-cluster
      clientSecret: secret
    resource:
      token-info-uri: http://localhost:8090/oauth/check_token
      preferTokenInfo: true
    basic:
      enabled: false
application:
  hostname: http://localhost:8080
  upload.path: /tmp/internal/kubernetes/uploads/
  cloud:
    storage:
      account.name: vtchk8sblueprinttfst
      container.name: filestorage
      account.key: secret
      connection: secret
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:/etc/config/application-prod.yml
---
spring:
  config:
    activate:
      on-profile: cloud
    import: file:/etc/config/cloud/application-cloud.yml