spring:
  profiles:
    active: dev
  application:
    name: filestorage
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
application:
  functions.url: https://vtch-functions.azurewebsites.net/api
  kafka:
    bootstrapAddress: localhost:9092
    topic: auditing
    stream:
      topic: reverseAuditing
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
    ch.valtech: DEBUG
application:
  hostname: http://localhost:8080
  upload.path: /tmp/internal/kubernetes/uploads/
  persistence.url: http://localhost:8081/api/v1/messages
  functions.key: functionKey
  token.url: http://localhost:8180/auth/realms/master/protocol/openid-connect/token
  cloud:
    storage:
      account.name: vtchk8sblueprinttfst
      container.name: filestorage
      account.key: secret
      connection: secret
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:/etc/config/application-prod.yml
---
spring:
  config:
    activate:
      on-profile: cloud
    import: file:/etc/config/cloud/application-cloud.yml
