spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
---
spring:
  config:
    activate:
      on-profile: dev
uploadPath: /tmp/internal/kubernetes/uploads/
---
spring:
  config:
    activate:
      on-profile: prod
    import: configtree:/etc/config/
---
spring:
  config:
    activate:
      on-profile: cloud
    import: configtree:/etc/config/cloud/