spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
---
spring:
  config:
    activate:
      on-profile: dev
application:
  hostname: http://localhost:8080
  upload.path: /tmp/internal/kubernetes/uploads/
  cloud:
    storage:
      account.name: vtchk8sblueprinttfst
      container.name: fileStorage
      account.key: 0r+mVj+YX8R4IC0boWZdWwhtbP83O9AcrEb1kWUjkw9D/RLg9scf27Ag64IYTVymgt5GNTV5SIyg2Nc3UnBfpg==
      connection: DefaultEndpointsProtocol=https;AccountName=vtchk8sblueprinttfst;AccountKey=0r+mVj+YX8R4IC0boWZdWwhtbP83O9AcrEb1kWUjkw9D/RLg9scf27Ag64IYTVymgt5GNTV5SIyg2Nc3UnBfpg==;EndpointSuffix=core.windows.net
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:/etc/config/application-prod.yml
---
spring:
  config:
    activate:
      on-profile: cloud
    import: file:/etc/config/cloud/application-cloud.yml