spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
---
spring:
  config:
    activate:
      on-profile: dev
hostname: http://localhost:8080
uploadPath: /tmp/internal/kubernetes/uploads/
storageAccountName: vtchk8sblueprinttfst
storageContainerName: fileStorage
secret:
  storageAccountKey: 0r+mVj+YX8R4IC0boWZdWwhtbP83O9AcrEb1kWUjkw9D/RLg9scf27Ag64IYTVymgt5GNTV5SIyg2Nc3UnBfpg==
  storageConnection: DefaultEndpointsProtocol=https;AccountName=vtchk8sblueprinttfst;AccountKey=0r+mVj+YX8R4IC0boWZdWwhtbP83O9AcrEb1kWUjkw9D/RLg9scf27Ag64IYTVymgt5GNTV5SIyg2Nc3UnBfpg==;EndpointSuffix=core.windows.net
---
spring:
  config:
    activate:
      on-profile: prod
    import: configtree:/etc/config/
---
spring:
  config:
    activate:
      on-profile: cloud
    import: configtree:/etc/config/cloud/