spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
---
spring:
  config:
    activate:
      on-profile: dev
upload.path: /tmp/internal/kubernetes/uploads/
---
spring:
  config:
    activate:
      on-profile: cloud
    import: configtree:/etc/config