spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
upload.path: /tmp/internal/kubernetes/uploads/
#    import: configtree:/etc/config - mounted volume in dev profile
---
spring:
  config:
    activate:
      on-profile: prod
