apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-api
  namespace: default
  labels:
    app: persistence-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: persistence-api
  template:
    metadata:
      labels:
        app: persistence-api
    spec:
      containers:
        - name: persistence-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mariadb-cm
                  key: database-url
          livenessProbe:
            httpGet:
              path: /persistence/actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /persistence/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: persistence-service
  labels:
    app: persistence-service
    service: persistence-service
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/persistence/actuator/prometheus'
      prometheus.io/port: '8081'
spec:
  selector:
    app: persistence-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081