apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: persistence
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - application-gateway
  http:
    - match:
        - uri:
            prefix: "/persistence/"
        - uri:
            prefix: "/persistence"
      rewrite:
        uri: "/"
      route:
        - destination:
            port:
              number: 8081
            host: persistence-service