apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: persistence-api
  name: persistence-config
  namespace: default
data:
  application-prod.yml: |-
    security:
      oauth2:
        client:
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
        resource:
          token-info-uri: http://authentication.default.svc.cluster.local:8080/auth/oauth/check_token
          preferTokenInfo: true
        basic:
          enabled: false
    application:
      token.url: http://authentication.default.svc.cluster.local:8080/auth/oauth/token