apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: persistence-api
  name: persistence-config
  namespace: default
data:
  application-prod.yml: |-
    application:
      token.url: https://vtch-aks-demo.duckdns.org/auth/realms/master/protocol/openid-connect/token
      token.issuer: https://vtch-aks-demo.duckdns.org/auth/realms/master