apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: authentication
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - application-gateway
  http:
    - match:
        - uri:
            prefix: "/auth"
        - uri:
            prefix: "/auth"
      rewrite:
        uri: "/"
      route:
        - destination:
            port:
              number: 8080
            host: authentication