apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: default
  labels:
    app: authentication
    service: authentication
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8090
  selector:
    app: authentication