name: Gradle Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    environment: Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Deploy to Docker Registry
        run: ./gradlew build jib -Pdocker_registry=${{ secrets.DOCKER_REGISTRY }} -Pdocker_registry_username=${{ secrets.DOCKER_USERNAME }} -Pdocker_registry_password=${{ secrets.DOCKER_PASSWORD }}
        env:
          CI_PASSWORD: ${{ secrets.CI_PASSWORD }}
      - name: Deploy to ArgoCD
        env:
          ARGOCD_SERVER: vtch-aks-demo-argocd.duckdns.org:80
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: >
          curl -sSL -o argocd http://vtch-aks-demo-argocd.duckdns.org:80/download/argocd-linux-amd64 &&
          chmod +x argocd &&
          ./argocd app set file-storage -p image.tag=${GITHUB_SHA} --plaintext --grpc-web &&
          ./argocd app set persistence -p image.tag=${GITHUB_SHA} --plaintext --grpc-web &&
          ./argocd app sync file-storage --plaintext --grpc-web &&
          ./argocd app sync persistence --plaintext --grpc-web &&
          ./argocd app sync bootstrap-cluster --plaintext --grpc-web
      - name: SonarQube Scan
        run: ./gradlew sonarqube -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
      - name: Publish API Documentation
        run: ./gradlew gitPublishPush --no-parallel -Prerun
        env:
          CI_PASSWORD: ${{ secrets.CI_PASSWORD }}
          GRGIT_USER: ${{ secrets.GIT_USER }}
          GRGIT_PASS: ${{ secrets.GIT_PASSWORD }}